### PR TITLE
added development setup to README

### PR DESCRIPTION
**Pull request by aahsue**
split the read me into two sections: development environment setup and deployment. added the development environment setup in accordance to the "Systems / Digital Waste Bin - Onboarding Guide" google doc.

### CODE REVIEW

**Review by patrickanguyen — CHANGES_REQUESTED** [review]

**Review by patrickanguyen — APPROVED** [review]
Good job broski

**Comment by okyang** [comment]
Great job @aahsue! @patrickanguyen and I reviewed. I decided to hold off on this pull request because I feel like we can reorganize the different ways setup instructions better. 

Some options I am considering so far:
- Combine the two sections since they are pretty similar when it comes to setup
- Create separate markdown files 
- Create a wiki page dedicated to different setups

Feel free to weigh in here or in slack 🌱

**Comment by aahsue** [comment]
sounds good owen! i think those suggestions make a lot of sense, and i was actually asking patrick about combining them previously as well!

**Comment by okyang** [comment]
@andreasuu how about this, we use your content for the readme section and then we create a new markdown file that we can link in the readme called **deployment options**

**deployment options* can include:
- Self-hosted deployment on your own personal LAMP server 
- PythonAnywhere 
- Cloud Options

**Comment by okyang** [comment]
Closing this pull request and addressing it in pull request #46.

**Pull request closed without merging**
